sudo: required

env:
  global:
    - DOCKER_VERSION=1.9.1  # Install Docker version 1.9.1

services:
  - docker

script:
  - docker build -t zokeber/postgresql:latest .
  - docker run -d -p 5432:5432 --name postgresql94 zokeber/postgresql
  - docker ps -a
